# Generated by Django 6.0.5 on 2026-06-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSplitter', '0002_user_otp_user_otp_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
