# Generated by Django 6.0.5 on 2026-06-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSplitter', '0003_alter_user_otp_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
