# Generated by Django 6.0.5 on 2026-06-05 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSplitter', '0005_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='ExpenseSplitter.group')),
            ],
        ),
    ]
