# Generated by Django 6.0.5 on 2026-06-08 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSplitter', '0006_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
