# Generated by Django 6.0.5 on 2026-06-08 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSplitter', '0007_budget_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=200)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reciept', models.ImageField(null=True, upload_to='receipts')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='ExpenseSplitter.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to=settings.AUTH_USER_MODEL)),
                ('skipped_member', models.ManyToManyField(default=[], related_name='skipped_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
