# Generated by Django 6.0.5 on 2026-06-08 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSplitter', '0008_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='skipped_member',
            field=models.ManyToManyField(default=list, related_name='skipped_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
