# Generated by Django 6.0.5 on 2026-06-09 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSplitter', '0009_alter_expense_skipped_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='reciept',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='expense',
            name='skipped_member',
            field=models.ManyToManyField(related_name='skipped_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
