# Generated by Django 6.0.4 on 2026-05-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author_Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimages',
            name='image',
            field=models.JSONField(),
        ),
    ]
