# Generated by Django 6.0.4 on 2026-05-09 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='std_image')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='Student_info.student')),
            ],
        ),
    ]
